<dec f='include/c++/10/bits/exception_ptr.h' l='64' type='std::__exception_ptr::exception_ptr std::current_exception()'/>
<dec f='include/c++/10/bits/exception_ptr.h' l='91' type='std::__exception_ptr::exception_ptr std::current_exception()'/>
<use f='include/c++/10/bits/exception_ptr.h' l='201' u='c' c='_ZSt18make_exception_ptrT_'/>
<use f='include/c++/10/bits/nested_exception.h' l='57' u='c' c='_ZNSt16nested_exceptionC1Ev'/>
<use f='include/c++/10/future' l='1350' u='c' c='_ZNKSt13__future_base12_Task_setterclEv'/>
<use f='include/c++/10/future' l='1373' u='c' c='_ZNKSt13__future_base12_Task_setterIT_T0_vEclEv'/>
<doc f='include/c++/10/bits/exception_ptr.h' l='60'>/** Obtain an exception_ptr to the currently handled exception. If there
   *  is none, or the currently handled exception is foreign, return the null
   *  value.
   */</doc>
<use f='qv2ray/test/catch.hpp' l='3034' u='c' c='_ZNK5Catch28ExceptionTranslatorRegistrar19ExceptionTranslator9translateB5cxx11EN9__gnu_cxx17__normal_iteratorIPKSt10unique_ptrIKNS_20IExceptionTransla11359245'/>
<use f='qv2ray/test/catch.hpp' l='10701' u='c' c='_ZNK5Catch27ExceptionTranslatorRegistry24translateActiveExceptionB5cxx11Ev'/>
<use f='qv2ray/test/catch.hpp' l='10708' u='c' c='_ZNK5Catch27ExceptionTranslatorRegistry24translateActiveExceptionB5cxx11Ev'/>
<use f='qv2ray/test/catch.hpp' l='10726' u='c' c='_ZNK5Catch27ExceptionTranslatorRegistry14tryTranslatorsB5cxx11Ev'/>
<use f='qv2ray/test/catch.hpp' l='12482' u='c' c='_ZN5Catch12_GLOBAL__N_111RegistryHub24registerStartupExceptionEv'/>
