<dec f='include/c++/10/bits/exception_ptr.h' l='70' type='void std::rethrow_exception(std::__exception_ptr::exception_ptr )'/>
<dec f='include/c++/10/bits/exception_ptr.h' l='92' type='void std::rethrow_exception(std::__exception_ptr::exception_ptr )'/>
<use f='include/c++/10/bits/nested_exception.h' l='70' u='c' c='_ZNKSt16nested_exception14rethrow_nestedEv'/>
<use f='include/c++/10/future' l='722' u='c' c='_ZNKSt14__basic_future13_M_get_resultEv'/>
<doc f='include/c++/10/bits/exception_ptr.h' l='69'>/// Throw the object pointed to by the exception_ptr.</doc>
<use f='qv2ray/test/catch.hpp' l='3033' u='c' c='_ZNK5Catch28ExceptionTranslatorRegistrar19ExceptionTranslator9translateB5cxx11EN9__gnu_cxx17__normal_iteratorIPKSt10unique_ptrIKNS_20IExceptionTransla11359245'/>
<use f='qv2ray/test/catch.hpp' l='10669' u='c' c='_ZNK5Catch27ExceptionTranslatorRegistry24translateActiveExceptionB5cxx11Ev'/>
<use f='qv2ray/test/catch.hpp' l='10687' u='c' c='_ZNK5Catch27ExceptionTranslatorRegistry14tryTranslatorsB5cxx11Ev'/>
<use f='qv2ray/test/catch.hpp' l='13249' u='c' c='_ZN5Catch7SessionC1Ev'/>
